client_id: 601-024-4735
client_name: A Noble Sweep
time_zone: America/Chicago
currency_code: USD
data_sources:
  google_ads:
    enabled: true
    mcc_id: null
  google_lsa:
    enabled: false
    import_method: csv
reporting:
  default_template: campaign_report.md.j2
  default_scope: LAST-30-DAYS
